1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

 Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [106]:
null = np.zeros(10) 
null[4] = 1
null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [13]:
np.array(4)+np.zeros(10)

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [19]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

 Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [20]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

Create a 3x3 identity matrix (★☆☆)

In [21]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 Create a 3x3x3 array with random values (★☆☆)

In [23]:
np.random.random((3,3,3))

array([[[0.74030248, 0.63543547, 0.39114028],
        [0.04126892, 0.2619819 , 0.6501334 ],
        [0.69686183, 0.10802117, 0.51055929]],

       [[0.70907652, 0.84249624, 0.07102861],
        [0.06512449, 0.09067493, 0.95411013],
        [0.8704686 , 0.22774422, 0.99707204]],

       [[0.35532299, 0.88850346, 0.23148466],
        [0.97191063, 0.94731275, 0.95257733],
        [0.53137901, 0.85202447, 0.50703689]]])

Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [28]:
array = np.random.random((10,10))

In [31]:
np.min(array)

0.0043566583973849715

In [32]:
np.max(array)

0.9791740094366879

10. Create a random vector of size 30 and find the mean value (★☆☆)

In [34]:
np.mean(np.random.random(30))

0.5612428251545024

11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [3]:
np.diag([1,2,3,4],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

12. Normalize a 5x5 random matrix (★☆☆)

In [119]:
a = np.random.random((5,5))

In [129]:
normalized = (a - np.mean(a))/np.std(a)

In [130]:
normalized

array([[-0.37365502, -0.79521591, -1.08658395, -0.96251944, -0.24143135],
       [-0.46658798,  0.74724174,  0.93145829, -0.79417751, -0.13947069],
       [ 0.8033225 ,  0.16974416,  1.79435176, -1.82170213,  0.13705271],
       [ 1.2528868 , -0.14130125,  1.53712844, -1.69310949, -0.77367677],
       [ 1.14646033,  1.25458826,  0.50378189,  0.3685735 , -1.3571589 ]])

13. How to find common values between two arrays? (★☆☆)

In [57]:
A = np.random.randint(0,80,size=(5,5))
A

array([[52,  8, 66, 69, 48],
       [61, 76, 24, 57, 29],
       [ 3,  6, 59, 24, 60],
       [27, 53, 25, 50, 31],
       [16, 25, 38, 42, 66]])

In [56]:
B = np.random.randint(0,80,size=(5,5))
B

array([[34, 34,  5, 66,  1],
       [79, 27, 27, 71,  8],
       [51, 16, 73, 14, 63],
       [28, 37, 44, 68, 18],
       [ 2, 21, 59, 14, 18]])

In [58]:
np.intersect1d(A,B)

array([ 8, 16, 27, 59, 66])

In [61]:
np.sort(np.random.random(10))

array([0.1424617 , 0.22618265, 0.2582109 , 0.29902015, 0.32395626,
       0.47322702, 0.61219195, 0.61775574, 0.74139178, 0.94620636])

15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [72]:
new_array = np.random.random(10)

print(new_array)

new_array[np.argmax(new_array)] = 0

print(new_array)

[0.87872176 0.9876178  0.51497196 0.09303341 0.98078738 0.28539211
 0.32758902 0.09729763 0.74275663 0.69092084]
[0.87872176 0.         0.51497196 0.09303341 0.98078738 0.28539211
 0.32758902 0.09729763 0.74275663 0.69092084]


16. Subtract the mean of each row of a matrix (★★☆)

In [73]:
a = np.random.rand(3, 4)
print(a)

[[0.8656263  0.94117219 0.56698634 0.50529104]
 [0.01999032 0.55699289 0.15140072 0.18901058]
 [0.38025271 0.57274112 0.17686689 0.42187384]]


In [75]:
b = a - a.mean(axis = 1, keepdims=True)

In [76]:
b

array([[ 0.14585733,  0.22140322, -0.15278263, -0.21447793],
       [-0.20935831,  0.32764426, -0.07794791, -0.04033805],
       [-0.00768093,  0.18480748, -0.21106675,  0.0339402 ]])

17. How to get the n largest values of an array (★★★)

In [77]:
Z = np.arange(10000)

In [78]:
Z

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [79]:
np.random.shuffle(Z)

In [82]:
np.argsort(Z)

array([7327, 3390, 7018, ..., 4943, 9984, 5420], dtype=int64)

In [83]:
np.argsort(Z)

array([7327, 3390, 7018, ..., 4943, 9984, 5420], dtype=int64)

In [86]:
sorted_array = Z[np.argsort(Z)]
sorted_array

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [87]:
sorted_array[-5:]

array([9995, 9996, 9997, 9998, 9999])

18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)

In [95]:
c = np.random.randint(0,10,(5,3))

c

array([[0, 4, 4],
       [6, 8, 1],
       [9, 8, 3],
       [2, 2, 3],
       [3, 4, 0]])

In [98]:
c_new = np.where(c>4,c,c**2)

In [99]:
c_new

array([[ 0, 16, 16],
       [ 6,  8,  1],
       [ 9,  8,  9],
       [ 4,  4,  9],
       [ 9, 16,  0]])